/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalibrationStatusBanner: typeof import('./src/components/CalibrationStatusBanner.vue')['default']
    ChartCanvas: typeof import('./src/components/ChartCanvas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    PostprocessPreviewDialog: typeof import('./src/components/PostprocessPreviewDialog.vue')['default']
    PreviewWorkspace: typeof import('./src/components/PreviewWorkspace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsAnalysisPanel: typeof import('./src/components/statistics/StatisticsAnalysisPanel.vue')['default']
    StatisticsDescriptionPanel: typeof import('./src/components/statistics/StatisticsDescriptionPanel.vue')['default']
    StatisticsExportFooter: typeof import('./src/components/statistics/StatisticsExportFooter.vue')['default']
    StatisticsImageCheckTable: typeof import('./src/components/statistics/StatisticsImageCheckTable.vue')['default']
    StatisticsMetricSelector: typeof import('./src/components/statistics/StatisticsMetricSelector.vue')['default']
    StatsSidebar: typeof import('./src/components/StatsSidebar.vue')['default']
    ZoomableImageDialog: typeof import('./src/components/ZoomableImageDialog.vue')['default']
  }
}
